// Puzzle configurations for the BODMAS Challenge - CORRECTED 15 EXCEL PUZZLES
// Difficulty 1: 1 blank per row | Difficulty 2: 2 blanks per row | Difficulty 3: 3 blanks per row
// rowOperators: 5 rows × 4 columns | colOperators: 4 rows × 5 columns

export const puzzleConfigs = [
  // Puzzle 1: Easy (2 blanks per row)
  {
    id: 1,
    name: "Puzzle 1: Easy",
    grid: [
      [
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "8", fixed: true },
        { value: "7", fixed: true },
        { value: "6", fixed: true },
      ],
      [
        { value: "5", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "3", fixed: true },
      ],
      [
        { value: "1", fixed: true },
        { value: "6", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "7", fixed: true },
      ],
      [
        { value: "8", fixed: true },
        { value: "4", fixed: true },
        { value: "3", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
      ],
      [
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "6", fixed: true },
        { value: "5", fixed: true },
        { value: "", fixed: false },
      ],
    ],
    rowOperators: [
      ["/", "-", "+", "*"],
      ["+", "-", "/", "*"],
      ["-", "+", "/", "*"],
      ["/", "+", "-", "*"],
      ["+", "-", "*", "/"],
    ],
    colOperators: [
      ["*", "-", "/", "*", "/"],
      ["+", "*", "+", "-", "+"],
      ["-", "+", "*", "/", "-"],
      ["/", "/", "-", "+", "*"],
    ],
    rowTargets: [37, 8, 16, 0, -24],
    colTargets: [44, -49, 23, 16, 4],
    answers: [
      [9, 3, 8, 7, 6],
      [5, 9, 4, 2, 3],
      [1, 6, 9, 3, 7],
      [8, 4, 3, 1, 5],
      [4, 2, 6, 5, 1],
    ],
    difficulty: 2,
  },

  // Puzzle 2: Easy (2 blanks per row)
  {
    id: 2,
    name: "Puzzle 2: Easy",
    grid: [
      [
        { value: "7", fixed: true },
        { value: "", fixed: false },
        { value: "4", fixed: true },
        { value: "5", fixed: true },
        { value: "", fixed: false },
      ],
      [
        { value: "5", fixed: true },
        { value: "8", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "4", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "6", fixed: true },
        { value: "8", fixed: true },
        { value: "4", fixed: true },
        { value: "", fixed: false },
      ],
      [
        { value: "8", fixed: true },
        { value: "", fixed: false },
        { value: "3", fixed: true },
        { value: "", fixed: false },
        { value: "5", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "", fixed: false },
        { value: "9", fixed: true },
        { value: "3", fixed: true },
      ],
    ],
    rowOperators: [
      ["/", "-", "+", "*"],
      ["+", "-", "/", "*"],
      ["-", "+", "/", "*"],
      ["/", "+", "-", "*"],
      ["+", "-", "*", "/"],
    ],
    colOperators: [
      ["*", "-", "/", "*", "/"],
      ["+", "*", "+", "-", "+"],
      ["-", "+", "*", "/", "-"],
      ["/", "/", "-", "+", "*"],
    ],
    rowTargets: [43, 5, 9, -5, -12],
    colTargets: [34, -45, 20, 12, -6],
    answers: [
      [7, 1, 4, 5, 8],
      [5, 8, 2, 1, 4],
      [1, 6, 8, 4, 7],
      [8, 4, 3, 2, 5],
      [4, 2, 6, 9, 3],
    ],
    difficulty: 2,
  },

  // Puzzle 3: Easy (2 blanks per row)
  {
    id: 3,
    name: "Puzzle 3: Easy",
    grid: [
      [
        { value: "8", fixed: true },
        { value: "2", fixed: true },
        { value: "", fixed: false },
        { value: "5", fixed: true },
        { value: "", fixed: false },
      ],
      [
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "1", fixed: true },
        { value: "3", fixed: true },
      ],
      [
        { value: "5", fixed: true },
        { value: "", fixed: false },
        { value: "8", fixed: true },
        { value: "", fixed: false },
        { value: "1", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "3", fixed: true },
        { value: "1", fixed: true },
        { value: "2", fixed: true },
        { value: "", fixed: false },
      ],
      [
        { value: "3", fixed: true },
        { value: "1", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "4", fixed: true },
      ],
    ],
    rowOperators: [
      ["/", "-", "+", "*"],
      ["+", "-", "/", "*"],
      ["-", "+", "/", "*"],
      ["/", "+", "-", "*"],
      ["+", "-", "*", "/"],
    ],
    colOperators: [
      ["*", "-", "/", "*", "/"],
      ["+", "*", "+", "-", "+"],
      ["-", "+", "*", "/", "-"],
      ["/", "/", "-", "+", "*"],
    ],
    rowTargets: [43, 5, -2, -10, -6],
    colTargets: [34, -58, 6, 11, -24],
    answers: [
      [8, 2, 6, 5, 9],
      [4, 7, 2, 1, 3],
      [5, 9, 8, 4, 1],
      [9, 3, 1, 2, 7],
      [3, 1, 5, 8, 4],
    ],
    difficulty: 2,
  },

  // Puzzle 4: Medium (3 blanks per row)
  {
    id: 4,
    name: "Puzzle 4: Medium",
    grid: [
      [
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "8", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "5", fixed: true },
        { value: "1", fixed: true },
        { value: "", fixed: false },
      ],
      [
        { value: "4", fixed: true },
        { value: "", fixed: false },
        { value: "1", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
      ],
      [
        { value: "", fixed: false },
        { value: "5", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "2", fixed: true },
      ],
      [
        { value: "7", fixed: true },
        { value: "2", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "", fixed: false },
      ],
    ],
    rowOperators: [
      ["+", "*", "/", "-"],
      ["/", "*", "-", "+"],
      ["+", "/", "*", "-"],
      ["*", "+", "-", "/"],
      ["+", "-", "*", "/"],
    ],
    colOperators: [
      ["+", "/", "+", "+", "/"],
      ["*", "+", "/", "*", "-"],
      ["/", "-", "-", "/", "+"],
      ["-", "*", "*", "-", "*"],
    ],
    rowTargets: [9, 18, 55, 10, -6],
    colTargets: [34, -1, -12, -1, -1],
    answers: [
      [5, 6, 4, 2, 8],
      [9, 3, 5, 1, 4],
      [4, 7, 1, 8, 5],
      [1, 5, 7, 4, 2],
      [7, 2, 3, 5, 1],
    ],
    difficulty: 3,
  },

  // Puzzle 5: Medium (3 blanks per row)
  {
    id: 5,
    name: "Puzzle 5: Medium",
    grid: [
      [
        { value: "1", fixed: true },
        { value: "7", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "", fixed: false },
      ],
      [
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "7", fixed: true },
        { value: "3", fixed: true },
      ],
      [
        { value: "9", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "5", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "5", fixed: true },
        { value: "7", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
      ],
      [
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "3", fixed: true },
        { value: "6", fixed: true },
        { value: "", fixed: false },
      ],
    ],
    rowOperators: [
      ["+", "*", "/", "-"],
      ["/", "*", "-", "+"],
      ["+", "/", "*", "-"],
      ["*", "+", "-", "/"],
      ["+", "-", "*", "/"],
    ],
    colOperators: [
      ["+", "/", "+", "+", "/"],
      ["*", "+", "/", "*", "-"],
      ["/", "-", "-", "/", "+"],
      ["-", "*", "*", "-", "*"],
    ],
    rowTargets: [6, 6, 28, 20, 2],
    colTargets: [0, -10, -8, 26, 0],
    answers: [
      [1, 7, 8, 4, 9],
      [2, 1, 5, 7, 3],
      [9, 3, 1, 8, 5],
      [3, 5, 7, 2, 1],
      [7, 4, 3, 6, 2],
    ],
    difficulty: 3,
  },

  // Puzzle 6: Medium (3 blanks per row)
  {
    id: 6,
    name: "Puzzle 6: Medium",
    grid: [
      [
        { value: "1", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "6", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "1", fixed: true },
        { value: "", fixed: false },
        { value: "7", fixed: true },
        { value: "", fixed: false },
      ],
      [
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "6", fixed: true },
        { value: "5", fixed: true },
      ],
      [
        { value: "4", fixed: true },
        { value: "", fixed: false },
        { value: "7", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
      ],
      [
        { value: "", fixed: false },
        { value: "9", fixed: true },
        { value: "4", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
      ],
    ],
    rowOperators: [
      ["+", "*", "/", "-"],
      ["/", "*", "-", "+"],
      ["+", "/", "*", "-"],
      ["*", "+", "-", "/"],
      ["+", "-", "*", "/"],
    ],
    colOperators: [
      ["+", "/", "+", "+", "/"],
      ["*", "+", "/", "*", "-"],
      ["/", "-", "-", "/", "+"],
      ["-", "*", "*", "-", "*"],
    ],
    rowTargets: [9, 8, 21, 25, 0],
    colTargets: [-2, -35, -14, 17, -1],
    answers: [
      [1, 7, 8, 3, 6],
      [2, 1, 8, 2, 9],
      [8, 3, 1, 6, 5],
      [4, 5, 7, 2, 1],
      [7, 9, 4, 8, 2],
    ],
    difficulty: 3,
  },

  // Puzzle 7: Very Easy (1 blank per row)
  {
    id: 7,
    name: "Puzzle 7: Very Easy",
    grid: [
      [
        { value: "", fixed: false },
        { value: "9", fixed: true },
        { value: "4", fixed: true },
        { value: "7", fixed: true },
        { value: "1", fixed: true },
      ],
      [
        { value: "7", fixed: true },
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "1", fixed: true },
        { value: "8", fixed: true },
      ],
      [
        { value: "5", fixed: true },
        { value: "1", fixed: true },
        { value: "", fixed: false },
        { value: "4", fixed: true },
        { value: "2", fixed: true },
      ],
      [
        { value: "1", fixed: true },
        { value: "6", fixed: true },
        { value: "3", fixed: true },
        { value: "", fixed: false },
        { value: "5", fixed: true },
      ],
      [
        { value: "8", fixed: true },
        { value: "2", fixed: true },
        { value: "6", fixed: true },
        { value: "3", fixed: true },
        { value: "", fixed: false },
      ],
    ],
    rowOperators: [
      ["+", "*", "-", "/"],
      ["-", "*", "/", "+"],
      ["/", "+", "*", "-"],
      ["*", "/", "+", "-"],
      ["/", "*", "-", "+"],
    ],
    colOperators: [
      ["-", "+", "/", "+", "*"],
      ["+", "/", "*", "-", "/"],
      ["/", "-", "-", "/", "+"],
      ["*", "*", "+", "*", "-"],
    ],
    rowTargets: [32, 7, 35, -1, 25],
    colTargets: [36, 1, 19, 2, 5],
    answers: [
      [3, 9, 4, 7, 1],
      [7, 4, 2, 1, 8],
      [5, 1, 8, 4, 2],
      [1, 6, 3, 2, 5],
      [8, 2, 6, 3, 4],
    ],
    difficulty: 1,
  },

  // Puzzle 8: Very Easy (1 blank per row)
  {
    id: 8,
    name: "Puzzle 8: Very Easy",
    grid: [
      [
        { value: "7", fixed: true },
        { value: "9", fixed: true },
        { value: "8", fixed: true },
        { value: "4", fixed: true },
        { value: "", fixed: false },
      ],
      [
        { value: "3", fixed: true },
        { value: "6", fixed: true },
        { value: "4", fixed: true },
        { value: "", fixed: false },
        { value: "8", fixed: true },
      ],
      [
        { value: "9", fixed: true },
        { value: "3", fixed: true },
        { value: "", fixed: false },
        { value: "6", fixed: true },
        { value: "1", fixed: true },
      ],
      [
        { value: "1", fixed: true },
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "3", fixed: true },
        { value: "5", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "5", fixed: true },
        { value: "7", fixed: true },
        { value: "4", fixed: true },
      ],
    ],
    rowOperators: [
      ["+", "*", "-", "/"],
      ["-", "*", "/", "+"],
      ["/", "+", "*", "-"],
      ["*", "/", "+", "-"],
      ["/", "*", "-", "+"],
    ],
    colOperators: [
      ["-", "+", "/", "+", "*"],
      ["+", "/", "*", "-", "/"],
      ["/", "-", "-", "/", "+"],
      ["*", "*", "+", "*", "-"],
    ],
    rowTargets: [77, -1, 44, 0, 12],
    colTargets: [58, 3, 17, -8, 17],
    answers: [
      [7, 9, 8, 4, 2],
      [3, 6, 4, 2, 8],
      [9, 3, 7, 6, 1],
      [1, 4, 2, 3, 5],
      [6, 2, 5, 7, 4],
    ],
    difficulty: 1,
  },

  // Puzzle 9: Very Easy (1 blank per row)
  {
    id: 9,
    name: "Puzzle 9: Very Easy",
    grid: [
      [
        { value: "7", fixed: true },
        { value: "", fixed: false },
        { value: "4", fixed: true },
        { value: "9", fixed: true },
        { value: "1", fixed: true },
      ],
      [
        { value: "9", fixed: true },
        { value: "5", fixed: true },
        { value: "2", fixed: true },
        { value: "", fixed: false },
        { value: "6", fixed: true },
      ],
      [
        { value: "4", fixed: true },
        { value: "1", fixed: true },
        { value: "", fixed: false },
        { value: "6", fixed: true },
        { value: "3", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "9", fixed: true },
        { value: "1", fixed: true },
        { value: "3", fixed: true },
        { value: "5", fixed: true },
      ],
      [
        { value: "8", fixed: true },
        { value: "2", fixed: true },
        { value: "6", fixed: true },
        { value: "7", fixed: true },
        { value: "", fixed: false },
      ],
    ],
    rowOperators: [
      ["+", "*", "-", "/"],
      ["-", "*", "/", "+"],
      ["/", "+", "*", "-"],
      ["*", "/", "+", "-"],
      ["/", "*", "-", "+"],
    ],
    colOperators: [
      ["-", "+", "/", "+", "*"],
      ["+", "/", "*", "-", "/"],
      ["/", "-", "-", "/", "+"],
      ["*", "*", "+", "*", "-"],
    ],
    rowTargets: [30, 5, 49, 16, 21],
    colTargets: [14, -5, 21, -4, 3],
    answers: [
      [7, 8, 4, 9, 1],
      [9, 5, 2, 1, 6],
      [8, 5, 4, 3, 7],
      [2, 9, 1, 6, 8],
      [4, 2, 3, 7, 1],
    ],
    difficulty: 1,
  },

  // Puzzle 10: Very Easy (1 blank per row)
  {
    id: 10,
    name: "Puzzle 10: Very Easy",
    grid: [
      [
        { value: "8", fixed: true },
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "5", fixed: true },
        { value: "1", fixed: true },
      ],
      [
        { value: "9", fixed: true },
        { value: "3", fixed: true },
        { value: "", fixed: false },
        { value: "1", fixed: true },
        { value: "6", fixed: true },
      ],
      [
        { value: "7", fixed: true },
        { value: "5", fixed: true },
        { value: "4", fixed: true },
        { value: "", fixed: false },
        { value: "3", fixed: true },
      ],
      [
        { value: "1", fixed: true },
        { value: "8", fixed: true },
        { value: "5", fixed: true },
        { value: "6", fixed: true },
        { value: "", fixed: false },
      ],
      [
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "1", fixed: true },
        { value: "9", fixed: true },
        { value: "7", fixed: true },
      ],
    ],
    rowOperators: [
      ["*", "/", "-", "+"],
      ["/", "+", "*", "-"],
      ["+", "-", "/", "*"],
      ["-", "*", "+", "/"],
      ["-", "/", "*", "+"],
    ],
    colOperators: [
      ["+", "*", "-", "/", "+"],
      ["*", "-", "/", "+", "/"],
      ["/", "+", "*", "-", "*"],
      ["-", "/", "+", "*", "-"],
    ],
    rowTargets: [12, 5, 6, -36, -8],
    colTargets: [68, 11, -7, -47, -2],
    answers: [
      [8, 4, 2, 5, 1],
      [9, 3, 8, 1, 6],
      [7, 5, 4, 2, 3],
      [1, 8, 5, 6, 2],
      [3, 2, 1, 9, 7],
    ],
    difficulty: 1,
  },

  // Puzzle 11: Very Easy (1 blank per row)
  {
    id: 11,
    name: "Puzzle 11: Very Easy",
    grid: [
      [
        { value: "5", fixed: true },
        { value: "9", fixed: true },
        { value: "", fixed: false },
        { value: "8", fixed: true },
        { value: "4", fixed: true },
      ],
      [
        { value: "6", fixed: true },
        { value: "3", fixed: true },
        { value: "8", fixed: true },
        { value: "", fixed: false },
        { value: "9", fixed: true },
      ],
      [
        { value: "4", fixed: true },
        { value: "5", fixed: true },
        { value: "2", fixed: true },
        { value: "1", fixed: true },
        { value: "", fixed: false },
      ],
      [
        { value: "2", fixed: true },
        { value: "", fixed: false },
        { value: "5", fixed: true },
        { value: "7", fixed: true },
        { value: "1", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "1", fixed: true },
        { value: "9", fixed: true },
        { value: "5", fixed: true },
      ],
    ],
    rowOperators: [
      ["*", "/", "-", "+"],
      ["/", "+", "*", "-"],
      ["+", "-", "/", "*"],
      ["-", "*", "+", "/"],
      ["-", "/", "*", "+"],
    ],
    colOperators: [
      ["+", "*", "-", "/", "+"],
      ["*", "-", "/", "+", "/"],
      ["/", "+", "*", "-", "*"],
      ["-", "/", "+", "*", "-"],
    ],
    rowTargets: [11, 25, 3, -11, -10],
    colTargets: [14, 24, -16, -60, 2],
    answers: [
      [5, 9, 3, 8, 4],
      [6, 3, 8, 4, 9],
      [4, 5, 2, 1, 3],
      [2, 4, 5, 7, 1],
      [3, 2, 1, 9, 5],
    ],
    difficulty: 1,
  },

  // Puzzle 12: Very Easy (1 blank per row)
  {
    id: 12,
    name: "Puzzle 12: Very Easy",
    grid: [
      [
        { value: "", fixed: false },
        { value: "7", fixed: true },
        { value: "1", fixed: true },
        { value: "4", fixed: true },
        { value: "2", fixed: true },
      ],
      [
        { value: "6", fixed: true },
        { value: "", fixed: false },
        { value: "8", fixed: true },
        { value: "2", fixed: true },
        { value: "9", fixed: true },
      ],
      [
        { value: "8", fixed: true },
        { value: "5", fixed: true },
        { value: "", fixed: false },
        { value: "1", fixed: true },
        { value: "3", fixed: true },
      ],
      [
        { value: "2", fixed: true },
        { value: "8", fixed: true },
        { value: "5", fixed: true },
        { value: "", fixed: false },
        { value: "1", fixed: true },
      ],
      [
        { value: "3", fixed: true },
        { value: "4", fixed: true },
        { value: "2", fixed: true },
        { value: "9", fixed: true },
        { value: "", fixed: false },
      ],
    ],
    rowOperators: [
      ["*", "/", "-", "+"],
      ["/", "+", "*", "-"],
      ["+", "-", "/", "*"],
      ["-", "*", "+", "/"],
      ["-", "/", "*", "+"],
    ],
    colOperators: [
      ["+", "*", "-", "/", "+"],
      ["*", "-", "/", "+", "/"],
      ["/", "+", "*", "-", "*"],
      ["-", "/", "+", "*", "-"],
    ],
    rowTargets: [33, 9, 1, -31, -10],
    colTargets: [26, 18, -7, -60, 0],
    answers: [
      [5, 7, 1, 4, 2],
      [6, 3, 2, 7, 3],
      [2, 1, 8, 4, 7],
      [6, 3, 4, 2, 8],
      [7, 4, 9, 5, 1],
    ],
    difficulty: 1,
  },

  // Puzzle 13: Easy (2 blanks per row)
  {
    id: 13,
    name: "Puzzle 13: Easy",
    grid: [
      [
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "9", fixed: true },
        { value: "3", fixed: true },
        { value: "6", fixed: true },
      ],
      [
        { value: "7", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "6", fixed: true },
        { value: "2", fixed: true },
      ],
      [
        { value: "1", fixed: true },
        { value: "4", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "7", fixed: true },
      ],
      [
        { value: "9", fixed: true },
        { value: "3", fixed: true },
        { value: "4", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
      ],
      [
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "3", fixed: true },
        { value: "7", fixed: true },
        { value: "", fixed: false },
      ],
    ],
    rowOperators: [
      ["*", "-", "/", "+"],
      ["+", "/", "-", "*"],
      ["-", "+", "/", "*"],
      ["/", "+", "-", "*"],
      ["+", "*", "-", "/"],
    ],
    colOperators: [
      ["*", "*", "-", "*", "/"],
      ["/", "/", "+", "-", "*"],
      ["-", "-", "/", "/", "-"],
      ["+", "+", "*", "+", "+"],
    ],
    rowTargets: [38, 3, 25, -1, 3],
    colTargets: [30, 13, 14, 23, 14],
    answers: [
      [5, 7, 9, 3, 6],
      [7, 8, 1, 6, 2],
      [1, 4, 8, 2, 7],
      [9, 3, 4, 1, 8],
      [4, 2, 3, 7, 1],
    ],
    difficulty: 2,
  },

  // Puzzle 14: Easy (2 blanks per row)
  {
    id: 14,
    name: "Puzzle 14: Easy",
    grid: [
      [
        { value: "8", fixed: true },
        { value: "", fixed: false },
        { value: "5", fixed: true },
        { value: "", fixed: false },
        { value: "6", fixed: true },
      ],
      [
        { value: "4", fixed: true },
        { value: "6", fixed: true },
        { value: "", fixed: false },
        { value: "7", fixed: true },
        { value: "", fixed: false },
      ],
      [
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "8", fixed: true },
        { value: "4", fixed: true },
        { value: "7", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "3", fixed: true },
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "8", fixed: true },
      ],
      [
        { value: "7", fixed: true },
        { value: "4", fixed: true },
        { value: "9", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
      ],
    ],
    rowOperators: [
      ["*", "-", "/", "+"],
      ["+", "/", "-", "*"],
      ["-", "+", "/", "*"],
      ["/", "+", "-", "*"],
      ["+", "*", "-", "/"],
    ],
    colOperators: [
      ["*", "*", "-", "*", "/"],
      ["/", "/", "+", "-", "*"],
      ["-", "-", "/", "/", "-"],
      ["+", "+", "*", "+", "+"],
    ],
    rowTargets: [57, -14, 15, -10, 38],
    colTargets: [17, 43, 21, 10, 7],
    answers: [
      [8, 7, 5, 1, 6],
      [4, 6, 2, 7, 3],
      [2, 1, 8, 4, 7],
      [6, 3, 4, 2, 8],
      [7, 4, 9, 5, 1],
    ],
    difficulty: 2,
  },

  // Puzzle 15: Easy (2 blanks per row) - CORRECTED
  {
    id: 15,
    name: "Puzzle 15: Easy",
    grid: [
      [
        { value: "5", fixed: true },
        { value: "7", fixed: true },
        { value: "4", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
      ],
      [
        { value: "4", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "7", fixed: true },
        { value: "3", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "1", fixed: true },
        { value: "6", fixed: true },
        { value: "3", fixed: true },
        { value: "", fixed: false },
      ],
      [
        { value: "8", fixed: true },
        { value: "", fixed: false },
        { value: "3", fixed: true },
        { value: "", fixed: false },
        { value: "4", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "4", fixed: true },
        { value: "", fixed: false },
        { value: "5", fixed: true },
        { value: "1", fixed: true },
      ],
    ],
    rowOperators: [
      ["*", "-", "/", "+"],
      ["+", "/", "-", "*"],
      ["-", "+", "/", "*"],
      ["/", "+", "-", "*"],
      ["+", "*", "-", "/"],
    ],
    colOperators: [
      ["*", "*", "-", "*", "/"],
      ["/", "/", "+", "-", "*"],
      ["-", "-", "/", "/", "-"],
      ["+", "+", "*", "+", "+"],
    ],
    rowTargets: [42, -14, 15, 3, 38],
    colTargets: [9, 44, 20, 16, 18],
    answers: [
      [5, 7, 4, 2, 9],
      [4, 6, 2, 7, 3],
      [2, 1, 6, 3, 7],
      [8, 2, 3, 1, 4],
      [7, 4, 9, 5, 1],
    ],
    difficulty: 2,
  },
    // Puzzle 16: Easy (2 blanks per row) - CORRECTED
  {
    id: 16,
    name: "Puzzle 16: Easy",
    grid: [
      [
        { value: "5", fixed: true },
        { value: "1", fixed: true },
        { value: "6", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
      ],
      [
        { value: "4", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "1", fixed: true },
        { value: "2", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "5", fixed: true },
        { value: "8", fixed: true },
        { value: "", fixed: false },
        { value: "1", fixed: true },
      ],
      [
        { value: "8", fixed: true },
        { value: "", fixed: false },
        { value: "3", fixed: true },
        { value: "2", fixed: true },
        { value: "", fixed: false },
      ],
      [
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "", fixed: false },
        { value: "9", fixed: true },
        { value: "3", fixed: true },
      ],
    ],
    rowOperators: [
      ["/", "-", "+", "*"],
      ["+", "-", "/", "*"],
      ["-", "+", "/", "*"],
      ["/", "+", "-", "*"],
      ["+", "-", "*", "/"],
    ],
    colOperators: [
      ["*", "-", "/", "*", "/"],
      ["+", "*", "+", "-", "+"],
      ["-", "+", "*", "/", "-"],
      ["/", "/", "-", "+", "*"],
    ],
    rowTargets: [27, 5, 4, -13, -18],
    colTargets: [19, -32, 19, 14, -24],
    answers: [
      [5, 1, 6, 7, 4],
      [4, 7, 3, 1, 2],
      [7, 5, 8, 4, 1],
      [8, 4, 3, 2, 9],
      [1, 2, 7, 9, 3],
    ],
    difficulty: 2,
  },

    // Puzzle 17: Easy (2 blanks per row) - CORRECTED
  {
    id: 17,
    name: "Puzzle 17: Easy",
    grid: [
      [
        { value: "8", fixed: true },
        { value: "2", fixed: true },
        { value: "4", fixed: true },
        { value: "7", fixed: true },
        { value: "6", fixed: true },
      ],
      [
        { value: "4", fixed: true },
        { value: "8", fixed: true },
        { value: "2", fixed: true },
        { value: "1", fixed: true },
        { value: "3", fixed: true },
      ],
      [
        { value: "1", fixed: true },
        { value: "6", fixed: true },
        { value: "8", fixed: true },
        { value: "4", fixed: true },
        { value: "7", fixed: true },
      ],
      [
        { value: "9", fixed: true },
        { value: "3", fixed: true },
        { value: "7", fixed: true },
        { value: "2", fixed: true },
        { value: "5", fixed: true },
      ],
      [
        { value: "3", fixed: true },
        { value: "1", fixed: true },
        { value: "6", fixed: true },
        { value: "8", fixed: true },
        { value: "2", fixed: true },
      ],
    ],
    rowOperators: [
      ["/", "-", "+", "*"],
      ["+", "-", "/", "*"],
      ["-", "+", "/", "*"],
      ["/", "+", "-", "*"],
      ["+", "-", "*", "/"],
    ],
    colOperators: [
      ["*", "-", "/", "*", "/"],
      ["+", "*", "+", "-", "+"],
      ["-", "+", "*", "/", "-"],
      ["/", "/", "-", "+", "*"],
    ],
    rowTargets: [42, 6, 9, 0, -20],
    colTargets: [30, -43, 52, 13, -1],
    answers: [
      [8, 2, 4, 7, 6],
      [4, 8, 2, 1, 3],
      [1, 6, 8, 4, 7],
      [9, 3, 7, 2, 5],
      [3, 1, 6, 8, 2],
    ],
    difficulty: 2,
  },


    // Puzzle 18: Medium (3 blanks per row) - CORRECTED
  {
    id: 18,
    name: "Puzzle 18: Medium",
    grid: [
      [
        { value: "", fixed: false },
        { value: "5", fixed: true },
        { value: "", fixed: false },
        { value: "3", fixed: true },
        { value: "", fixed: false },
      ],
      [
        { value: "3", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "2", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "1", fixed: true },
        { value: "", fixed: false },
        { value: "5", fixed: true },
      ],
      [
        { value: "4", fixed: true },
        { value: "9", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "", fixed: false },
      ],
      [
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "8", fixed: true },
        { value: "", fixed: false },
      ],
    ],
    rowOperators: [
      ["+", "*", "/", "-"],
      ["/", "*", "-", "+"],
      ["+", "/", "*", "-"],
      ["*", "+", "-", "/"],
      ["+", "-", "*", "/"],
    ],
    colOperators: [
      ["+", "/", "+", "+", "/"],
      ["*", "+", "/", "*", "-"],
      ["/", "-", "-", "/", "+"],
      ["-", "*", "*", "-", "*"],
    ],
    rowTargets: [8, 13, 21, 41, 9],
    colTargets: [0, -46, 1, 16, 3],
    answers: [
      [1, 5, 9, 3, 8],
      [3, 1, 6, 7, 2],
      [8, 3, 1, 6, 5],
      [4, 9, 7, 2, 1],
      [7, 6, 2, 8, 4],
    ],
    difficulty: 3,
  },

      // Puzzle 19: Medium (3 blanks per row) - CORRECTED
  {
    id: 19,
    name: "Puzzle 19: Medium",
    grid: [
      [
        { value: "", fixed: false },
        { value: "4", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "6", fixed: true },
      ],
      [
        { value: "5", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "7", fixed: true },
        { value: "", fixed: false },
      ],
      [
        { value: "", fixed: false },
        { value: "6", fixed: true },
        { value: "2", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
      ],
      [
        { value: "3", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "1", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "9", fixed: true },
        { value: "6", fixed: true },
        { value: "", fixed: false },
      ],
    ],
    rowOperators: [
      ["+", "*", "/", "-"],
      ["/", "*", "-", "+"],
      ["+", "/", "*", "-"],
      ["*", "+", "-", "/"],
      ["+", "-", "*", "/"],
    ],
    colOperators: [
      ["+", "/", "+", "+", "/"],
      ["*", "+", "/", "*", "-"],
      ["/", "-", "-", "/", "+"],
      ["-", "*", "*", "-", "*"],
    ],
    rowTargets: [11, 25, 28, 18, -20],
    colTargets: [12, -5, -52, 10, 0],
    answers: [
      [1, 4, 8, 2, 6],
      [5, 1, 6, 7, 2],
      [9, 6, 2, 8, 5],
      [3, 5, 7, 4, 1],
      [4, 3, 9, 6, 2],
    ],
    difficulty: 3,
  },

      // Puzzle 20: Very Easy (1 blanks per row) - CORRECTED
  {
    id: 20,
    name: "Puzzle 20: Very Easy",
    grid: [
      [
        { value: "3", fixed: true },
        { value: "9", fixed: true },
        { value: "", fixed: false },
        { value: "7", fixed: true },
        { value: "1", fixed: true },
      ],
      [
        { value: "8", fixed: true },
        { value: "5", fixed: true },
        { value: "4", fixed: true },
        { value: "", fixed: false },
        { value: "9", fixed: true },
      ],
      [
        { value: "7", fixed: true },
        { value: "", fixed: false },
        { value: "5", fixed: true },
        { value: "6", fixed: true },
        { value: "3", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "6", fixed: true },
        { value: "2", fixed: true },
        { value: "3", fixed: true },
        { value: "5", fixed: true },
      ],
      [
        { value: "4", fixed: true },
        { value: "2", fixed: true },
        { value: "6", fixed: true },
        { value: "9", fixed: true },
        { value: "", fixed: false },
      ],
    ],
    rowOperators: [
      ["+", "*", "-", "/"],
      ["-", "*", "/", "+"],
      ["/", "+", "*", "-"],
      ["*", "/", "+", "-"],
      ["/", "*", "-", "+"],
    ],
    colOperators: [
      ["-", "+", "/", "+", "*"],
      ["+", "/", "*", "-", "/"],
      ["/", "-", "-", "/", "+"],
      ["*", "*", "+", "*", "-"],
    ],
    rowTargets: [68, 7, 34, 1, 10],
    colTargets: [23, 2, 14, -9, 1],
    answers: [
      [3, 9, 8, 7, 1],
      [8, 5, 4, 2, 9],
      [7, 1, 5, 6, 3],
      [1, 6, 2, 3, 5],
      [4, 2, 6, 9, 7],
    ],
    difficulty: 1,
  },

        // Puzzle 21: Very Easy (1 blanks per row) - CORRECTED
  {
    id: 21,
    name: "Puzzle 21: Very Easy",
    grid: [
      [
        { value: "8", fixed: true },
        { value: "7", fixed: true },
        { value: "4", fixed: true },
        { value: "5", fixed: true },
        { value: "1", fixed: true },
      ],
      [
        { value: "7", fixed: true },
        { value: "4", fixed: true },
        { value: "2", fixed: true },
        { value: "1", fixed: true },
        { value: "8", fixed: true },
      ],
      [
        { value: "5", fixed: true },
        { value: "1", fixed: true },
        { value: "8", fixed: true },
        { value: "4", fixed: true },
        { value: "2", fixed: true },
      ],
      [
        { value: "1", fixed: true },
        { value: "6", fixed: true },
        { value: "3", fixed: true },
        { value: "2", fixed: true },
        { value: "7", fixed: true },
      ],
      [
        { value: "4", fixed: true },
        { value: "2", fixed: true },
        { value: "9", fixed: true },
        { value: "3", fixed: true },
        { value: "5", fixed: true },
      ],
    ],
    rowOperators: [
      ["+", "*", "-", "/"],
      ["-", "*", "/", "+"],
      ["/", "+", "*", "-"],
      ["*", "/", "+", "-"],
      ["/", "*", "-", "+"],
    ],
    colOperators: [
      ["-", "+", "/", "+", "*"],
      ["+", "/", "*", "-", "/"],
      ["/", "-", "-", "/", "+"],
      ["*", "*", "+", "*", "-"],
    ],
    rowTargets: [31, 7, 35, -3, 20],
    colTargets: [21, -1, 22, 0, 6],
    answers: [
      [8, 7, 4, 5, 1],
      [7, 4, 2, 1, 8],
      [5, 1, 8, 4, 2],
      [1, 6, 3, 2, 7],
      [4, 2, 9, 3, 5],
    ],
    difficulty: 1,
  },
        // Puzzle 22: Very Easy (1 blanks per row) - CORRECTED
  {
    id: 22,
    name: "Puzzle 22: Very Easy",
    grid: [
      [
        { value: "1", fixed: true },
        { value: "8", fixed: true },
        { value: "4", fixed: true },
        { value: "9", fixed: true },
        { value: "", fixed: false },
      ],
      [
        { value: "8", fixed: true },
        { value: "1", fixed: true },
        { value: "9", fixed: true },
        { value: "", fixed: false },
        { value: "4", fixed: true },
      ],
      [
        { value: "4", fixed: true },
        { value: "9", fixed: true },
        { value: "", fixed: false },
        { value: "1", fixed: true },
        { value: "2", fixed: true },
      ],
      [
        { value: "2", fixed: true },
        { value: "", fixed: false },
        { value: "5", fixed: true },
        { value: "7", fixed: true },
        { value: "1", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "1", fixed: true },
        { value: "4", fixed: true },
        { value: "3", fixed: true },
      ],
    ],
    rowOperators: [
      ["*", "/", "-", "+"],
      ["/", "+", "*", "-"],
      ["+", "-", "/", "*"],
      ["-", "*", "+", "/"],
      ["-", "/", "*", "+"],
    ],
    colOperators: [
      ["+", "*", "-", "/", "+"],
      ["*", "-", "/", "+", "/"],
      ["/", "+", "*", "-", "*"],
      ["-", "/", "+", "*", "-"],
    ],
    rowTargets: [0, 31, 7, -11, 1],
    colTargets: [11, 1, -10, -24, 6],
    answers: [
      [1, 8, 4, 9, 7],
      [8, 1, 9, 3, 4],
      [4, 9, 3, 1, 2],
      [2, 4, 5, 7, 1],
      [6, 2, 1, 4, 3],
    ],
    difficulty: 1,
  },

          // Puzzle 23: Very Easy (1 blanks per row) - CORRECTED
  {
    id: 23,
    name: "Puzzle 23: Very Easy",
    grid: [
      [
        { value: "5", fixed: true },
        { value: "9", fixed: true },
        { value: "3", fixed: true },
        { value: "8", fixed: true },
        { value: "2", fixed: true },
      ],
      [
        { value: "4", fixed: true },
        { value: "2", fixed: true },
        { value: "8", fixed: true },
        { value: "1", fixed: true },
        { value: "9", fixed: true },
      ],
      [
        { value: "8", fixed: true },
        { value: "5", fixed: true },
        { value: "4", fixed: true },
        { value: "2", fixed: true },
        { value: "3", fixed: true },
      ],
      [
        { value: "2", fixed: true },
        { value: "6", fixed: true },
        { value: "5", fixed: true },
        { value: "7", fixed: true },
        { value: "1", fixed: true },
      ],
      [
        { value: "7", fixed: true },
        { value: "3", fixed: true },
        { value: "1", fixed: true },
        { value: "9", fixed: true },
        { value: "5", fixed: true },
      ],
    ],
    rowOperators: [
      ["*", "/", "-", "+"],
      ["/", "+", "*", "-"],
      ["+", "-", "/", "*"],
      ["-", "*", "+", "/"],
      ["-", "/", "*", "+"],
    ],
    colOperators: [
      ["+", "*", "-", "/", "+"],
      ["*", "-", "/", "+", "/"],
      ["/", "+", "*", "-", "*"],
      ["-", "/", "+", "*", "-"],
    ],
    rowTargets: [9, 1, 7, -21, -15],
    colTargets: [14, 15, -6, -53, 0],
    answers: [
      [5, 9, 3, 8, 2],
      [4, 2, 8, 1, 9],
      [8, 5, 4, 2, 3],
      [2, 6, 5, 7, 1],
      [7, 3, 1, 9, 5],
    ],
    difficulty: 1,
  },

            // Puzzle 24: Very (2 blanks per row) - CORRECTED
  {
    id: 24,
    name: "Puzzle 24:Easy",
    grid: [
      [
        { value: "", fixed: false },
        { value: "4", fixed: true },
        { value: "", fixed: false },
        { value: "3", fixed: true },
        { value: "6", fixed: true },
      ],
      [
        { value: "4", fixed: true },
        { value: "", fixed: false },
        { value: "1", fixed: true },
        { value: "5", fixed: true },
        { value: "", fixed: false },
      ],
      [
        { value: "2", fixed: true },
        { value: "1", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "7", fixed: true },
      ],
      [
        { value: "6", fixed: true },
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "", fixed: false },
        { value: "8", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "5", fixed: true },
        { value: "6", fixed: true },
        { value: "7", fixed: true },
        { value: "", fixed: false },
      ],
    ],
    rowOperators: [
      ["*", "-", "/", "+"],
      ["+", "/", "-", "*"],
      ["-", "+", "/", "*"],
      ["/", "+", "-", "*"],
      ["+", "*", "-", "/"],
    ],
    colOperators: [
      ["*", "*", "-", "*", "/"],
      ["/", "/", "+", "-", "*"],
      ["-", "-", "/", "/", "-"],
      ["+", "+", "*", "+", "+"],
    ],
    rowTargets: [35, -3, 15, -4, 27],
    colTargets: [14, 34, 20, 20, 7],
    answers: [
      [8, 4, 9, 3, 6],
      [4, 8, 1, 5, 3],
      [2, 1, 4, 2, 7],
      [6, 3, 2, 1, 8],
      [4, 5, 6, 7, 1],
    ],
    difficulty: 2,
  },

            // Puzzle 25: Very (2 blanks per row) - CORRECTED
  {
    id: 25,
    name: "Puzzle 25:Very",
    grid: [
      [
        { value: "5", fixed: true },
        { value: "7", fixed: true },
        { value: "8", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
      ],
      [
        { value: "4", fixed: true },
        { value: "6", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "3", fixed: true },
      ],
      [
        { value: "2", fixed: true },
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "3", fixed: true },
        { value: "7", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "", fixed: false },
        { value: "2", fixed: true },
        { value: "1", fixed: true },
        { value: "8", fixed: true },
      ],
      [
        { value: "", fixed: false },
        { value: "4", fixed: true },
        { value: "9", fixed: true },
        { value: "5", fixed: true },
        { value: "", fixed: false },
      ],
    ],
    rowOperators: [
      ["*", "-", "/", "+"],
      ["+", "/", "-", "*"],
      ["-", "+", "/", "*"],
      ["/", "+", "-", "*"],
      ["+", "*", "-", "/"],
    ],
    colOperators: [
      ["*", "*", "-", "*", "/"],
      ["/", "/", "+", "-", "*"],
      ["-", "-", "/", "/", "-"],
      ["+", "+", "*", "+", "+"],
    ],
    rowTargets: [42, -11, 15, -4, 38],
    colTargets: [11, 43, 34, 30, 14],
    answers: [
      [5, 7, 8, 4, 9],
      [4, 6, 1, 7, 3],
      [2, 1, 6, 3, 7],
      [6, 3, 2, 1, 8],
      [7, 4, 9, 5, 1],
    ],
    difficulty: 2,
  },

];

// Default puzzle configuration
const puzzleConfig = {
  defaultPuzzleId: 1,  // Change this value to set a different default puzzle
};

export default puzzleConfig;
